<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##The price of one apple and one orange

In [5]:
import numpy as np
from scipy.linalg import solve
A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)
X = solve(A,B)
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


In [6]:
inv_A = np.linalg.inv(A)
print(inv_A)
X = np.linalg.inv(A).dot(B)
print(X)

[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[10.]
 [15.]]


In [7]:
X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]


##Solving for three linear equations with unkown variables of x, y, and z

In [8]:
#4x+3y+2z = 25
#-2x+2y+3z = -10
#3x-5y+2z = -4

A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B = np.array([[25],[-10],[-4]])
print(A)
print(B)
X = solve(A,B)
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 25]
 [-10]
 [ -4]]
[[ 5.]
 [ 3.]
 [-2.]]
