<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/CODING_ACTIVITY_3_(LINEAR_TRANSFORMATION)_WEEK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CODING ACTIVITY 3

##Create a NumPy program that solves for the unknown variables of linear systems:

4x +10y+8z = 44

10x+26y+26z = 128

8x+26y+61z = 214

In [2]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,61]]) #creation of matrix A
print(A)
print("------------")
inv_A = np.linalg.inv(A) #inverse of matrix A
print(inv_A)
print("------------")
B = np.array([[44],[128],[214]]) #creation of matrix B (constants of the eq.)
print(B)
print("------------")
X = np.dot(inv_A,B) #dot product (values of x,y,z)
print(X)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
------------
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
------------
[[ 44]
 [128]
 [214]]
------------
[[-8.]
 [ 6.]
 [ 2.]]
