<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/CODING_ACTIVITY_3_(LINEAR_TRANSFORMATION).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CODING ACTIVITY 3

In [13]:
import numpy as np
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #creation of matrix A
print(A)
print("------------")
inv_A = np.linalg.inv(A) #inverse of matrix A
print(inv_A)
print("------------")
B = np.array([[25],[-10],[-4]]) #creation of matrix B (constants of the eq.)
print(B)
print("------------")
X = np.dot(inv_A,B) #dot product (values of x,y,z)
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
------------
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]
------------
[[ 25]
 [-10]
 [ -4]]
------------
[[ 5.]
 [ 3.]
 [-2.]]
