<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a Python Program to inverse and transpose a 4x4 matrix, A = ([[6,1,1,3],[4,-2,5,1],[2,8,7,6], [3,1,9,7]])

In [8]:
##Python Program to Inverse

import numpy as np
A = np.array([[1,2],[4,7]])
invA = np.linalg.inv(A)
print(invA)


C=np.dot(A,invA)
print(C)


##Python Program to Transpose with 3x3 Matrix

a = np.array([[6,1,1],[4,-2,5],[2,8,7]])
b = np.transpose(a)
print(a, "\n\n")
print(b)

[[-7.  2.]
 [ 4. -1.]]
[[1. 0.]
 [0. 1.]]
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 


[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [5]:
import numpy as np #numpy library
A = ([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]]) #Matrix A
invA = np.linalg.inv(A) #function to be used for inversing matrix
print(invA) #printing inverse matrix


[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


In [6]:
transA = np.transpose(A) #function to be used for transposing matrix
print(transA) #printing transpose matrix

[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
