<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/DEMO_2_(LINEAR_TRANSFORMATION).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##To find the inverse of a matrix, the matrix is passed to the linalg.inv() of the NumPy module:


4x + 3y = 20

-5x + 9y = 26

In [14]:
import numpy as np
A = np.array([[4,3],[-5,9]])
print(A)
print("------------")
inv_A =np.linalg.inv(A)
print(inv_A)
print("------------")
B = np.array([[20],[26]])
X=np.linalg.inv(A).dot(B) #method in solving values of unknown var.
print(X)
print("------------")
X=np.dot(inv_A,B) #alternative method in solving values of unknown var.
print(X)

[[ 4  3]
 [-5  9]]
------------
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]
------------
[[2.]
 [4.]]
------------
[[2.]
 [4.]]


Let's now solve a system of three linear equations shown below:

4x + 3y + 2z = 25

-2x + 2y + 3z = -10

3x - 5y + 2z = -4

In [15]:
import numpy as np
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #creation of matrix A
print(A)
print("------------")
inv_A = np.linalg.inv(A) #inverse of matrix A
print(inv_A)
print("------------")
B = np.array([[25],[-10],[-4]]) #creation of matrix B (constants of the eq.)
print(B)
print("------------")
X = np.dot(inv_A,B) #dot product (values of x,y,z)
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
------------
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]
------------
[[ 25]
 [-10]
 [ -4]]
------------
[[ 5.]
 [ 3.]
 [-2.]]


##APPLICATION (ORANGE AND APPLE)

In [16]:
import numpy as np
A = np.array([[20,10],[17,22]])
print(A)
print("------------")
inv_A =np.linalg.inv(A)
print(inv_A)
print("------------")
B = np.array([[350],[500]])
X=np.dot(inv_A,B)
print(X)


[[20 10]
 [17 22]]
------------
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
------------
[[10.]
 [15.]]


TO CHECK IF THE ANSWER IS CORRECT

In [17]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]
