<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/FINAL_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION 1

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)


In [52]:
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
totalamount = np.linalg.inv(eq1).dot(eq2)
print (totalamount)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 


##EXPLANATION TO #2: This is not running because of line 5, the inverse of the matrix does not exist. Also the error kept on saying singular matrix making the determinant zero. If the determinant of the matrix is zero, then it will not have an inverse; the matrix is then said to be singular.

In [53]:
import numpy as np
A = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]]) #creation of matrix A
print(A)
print("------------")
inv_A = np.linalg.inv(A) #inverse of matrix A
print(inv_A)
print("------------")
B = np.array([[5], [15], [-20]]) #creation of matrix B (constants of the eq.)
print(B)
print("------------")
X = np.dot(inv_A,B) #dot product (values of x,y,z)
print(X)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
------------


LinAlgError: ignored

QUESTION 3

Problem 3. Consider the matrix, (40 points)
Find the eigenvalue/s
Find the eigenvectors

In [51]:
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
s,t = np.linalg.eig(A)
print("The eigenvalue/s is/are: ", s)
print("The right eigenvectors are: ", t)

The eigenvalue/s is/are:  [-1.  3.  2.]
The right eigenvectors are:  [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
