<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

print(np.dot(A,B))

Z = D+D
print(Z)

Y = 2*C
print(Y)



[[22 28]
 [49 64]]
[[2 4]
 [6 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [42]:
M = np.matrix([5,3,-1])
print(M.shape)
print(M.ndim)
print(M.size)
print(type(M))


(1, 3)
2
3
<class 'numpy.matrix'>
