<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Representing Vectors

In [ ]:
import numpy as np

In [ ]:
A = np.array ([4, 3])

In [ ]:
B = np.array([2, -5])

In [ ]:
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


##Describing Vectors in NumPy

In [ ]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0, 1, -1])
pool = np.array([ball1, ball2])
pool.shape
pool.ndim

2

In [ ]:
U = np.array([[1,2,3],[4,5,6]])
U.shape #rows and column
U.size

6

##Space


Addition of vectors

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [ ]:
resultant = np.add(addend1, addend2)
resultant

array([1, 1, 0])

Subtraction of Vectors

In [ ]:
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [ ]:
resultant = np.subtract(addend1, addend2)
resultant

array([-1, -1,  0])

In [ ]:
Scaling

In [ ]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

Cross Product

In [ ]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute cross product of A and B
cross = np.cross(A,B)
print(cross)

11
