<a href="https://colab.research.google.com/github/viaa-bot/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations


In [1]:
from numpy import array

In [2]:
import numpy as np

In [6]:
A = np.array([[-5, 0], [4, 1]]) 

In [7]:
B = np.array([[6, -3], [2, 3]]) 

ADDITION


In [24]:
print(np.add(A, B))

[[ 1 -3]
 [ 6  4]]


DIFFERRENCE 1

In [22]:
print(np.subtract(B, A))

[[11 -3]
 [-2  2]]


DIFFERRENCE 2

In [23]:
print(np.subtract(A, B))

[[-11   3]
 [  2  -2]]
